### ISSUE TITLE
Reg. Creating Map But Need Calibration Parameters First

### ISSUE THREAD

**Issue by ksivakumar** [ethz-asl/maplab#81]
Hi,

From your Running ROVIOLI in VIO mode page, it says you need Camera calibration, IMU parameters maplab, and IMU parameters Rovio. I am using a ZED stereo camera and using the left.yaml and right.yaml calibration files from the github repo https://github.com/willdzeng/zed_cpu_ros. How can I convert these calibration files to the camera calibration file maplab requires or is there no need to? Also could you please give me some guidance on how I can create the IMU parameters maplab and IMU parameters Rovio files? 

For your convenience, here are the left.yaml and right.yaml files respectively from the repo mentioned above:

```
image_width: 1280
image_height: 720
camera_name: camera/left
camera_matrix:
  rows: 3
  cols: 3
  data: [696.262741, 0.000000, 664.582790, 0.000000, 696.715205, 331.199610, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.174138, 0.025148, -0.000023, 0.001127, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.999987, 0.000814, 0.005020, -0.000801, 0.999996, -0.002658, -0.005022, 0.002654, 0.999984]
projection_matrix:
  rows: 3
  cols: 4
  data: [696.388858, 0.000000, 648.123726, 0.000000, 0.000000, 696.388858, 345.289268, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
```
```
image_width: 1280
image_height: 720
camera_name: camera/right
camera_matrix:
  rows: 3
  cols: 3
  data: [697.561169, 0.000000, 619.174651, 0.000000, 697.422254, 364.054801, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.167196, 0.022090, 0.000330, -0.000437, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.999946, -0.000419, -0.010401, 0.000447, 0.999996, 0.002653, 0.010400, -0.002658, 0.999942]
projection_matrix:
  rows: 3
  cols: 4
  data: [696.388858, 0.000000, 648.123726, -359.466975, 0.000000, 696.388858, 345.289268, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
```

Thank you for any help, and I apologize in advance if this is too general of a question to ask, I am not too familiar with calibration.
